### ISSUE TITLE
CouldNotPerformException applyAction(ActionDescription) can not be invoked

### ISSUE THREAD

**Issue by jdaberkow** [openbase/bco.dal#51] opened 2017-07-06 16:40 UTC
Lately my bco console is getting flooded with error messages of the following kind:

(see https://pastebin.com/veuUMhLm for a more detailed log)

Perhaps this occurs since I am not able to merge the current master into my feature branch on remote side. If so, maybe it can be pointed out which commit I need to cherry-pick in order to solve this issue?

```
17:02:48.544 [Thread-1238] ERROR o.o.b.d.l.l.u.PowerSwitchController ═╦═⚀ org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class applyAction(ActionDescription)]!
17:02:48.544 [Thread-1238] ERROR o.o.b.d.l.l.u.PowerSwitchController  ╚══╦═⚀ Could not invoke Method[Class applyAction(ActionDescription)]!
17:02:48.544 [Thread-1238] ERROR o.o.b.d.l.l.u.PowerSwitchController     ╚══╦═⚀ InvocationTargetException
17:02:48.544 [Thread-1238] ERROR o.o.b.d.l.l.u.PowerSwitchController        ╚══╦═⚀ Could not apply action!
17:02:48.544 [Thread-1238] ERROR o.o.b.d.l.l.u.PowerSwitchController           ╚══╦═⚀ Could not initialize class org.openbase.bco.dal.lib.action.ActionImpl!
17:02:48.544 [Thread-1238] ERROR o.o.b.d.l.l.u.PowerSwitchController              ╚══╦═⚀ Given ActionDescription[] is invalid!
17:02:48.544 [Thread-1238] ERROR o.o.b.d.l.l.u.PowerSwitchController                 ╚════⚀ Referred unit is not compatible with the registered unit controller!
17:02:48.544 [Thread-1238] ERROR o.o.b.d.l.l.u.PowerSwitchController =====================================
Jul 06, 2017 5:02:48 PM rsb.patterns.LocalMethod internalNotify
WARNUNG: Exception during method invocation in participant: /home/kitchen/powerswitch/s8_c6/ctrl/applyAction/. Exception message: org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class applyAction(ActionDescription)]!
```

**Comment by DivineThreepwood** [comment] 2017-07-07 01:36
I can confirm this bug.
It occurs if I trigger a scene via a physical button where the scene is just performing the power state operation "off" on the root location. Triggering "off" on the root location via openhab still works so maybe the scene action deserialization is broken?

**Comment by jdaberkow** [comment] 2017-07-07 11:58
I checked again and noticed, that this only happens for me during the simulation mode and is therefore not connected to deprecated remotes. Maybe the direct manipulation of controllers lead to this issue.

**Comment by pLeminoq** [comment] 2017-07-13 10:55
I have reproduced this bug by triggering scenes which triggered state changes on locations. In this case the location will apply an action by calling the same method for every according unit remote. The problem was that in this call the action description has not been updated and therefore the id of the location in the action description remained which caused the error. It should be fixed by commit:

* 64287a09df264a8a3cc3e516b64e68cb41708f12

**Closed** 2017-10-20 09:24 UTC
Labels: bug
